volumes:
  postgres_data:
  uploads:

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: audio_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: audio_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
